sonar.projectKey=tasklist-frontend-catherine
sonar.projectName=TaskList Frontend - Catherine
sonar.projectVersion=1.0

# Chemin des sources analysées
sonar.sources=src
sonar.exclusions=src/__tests__/**,dist/**,node_modules/**

# Chemin des tests
sonar.tests=src/__tests__
sonar.test.inclusions=src/__tests__/**/*.test.ts,src/__tests__/**/*.test.tsx

# Rapport de couverture (généré par vitest --coverage, reporter lcov)
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8